# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from rivalika_sdk.models.commercial_import_detail_envelope_data_row_errors_inner import CommercialImportDetailEnvelopeDataRowErrorsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CommercialImportDetailEnvelopeData(BaseModel):
    """
    CommercialImportDetailEnvelopeData
    """ # noqa: E501
    id: UUID
    kind: StrictStr
    status: StrictStr
    file_name: StrictStr
    dry_run: StrictBool
    sheet_name: Optional[StrictStr]
    total_rows: Annotated[int, Field(strict=True, ge=0)]
    imported_rows: Annotated[int, Field(strict=True, ge=0)]
    rejected_rows: Annotated[int, Field(strict=True, ge=0)]
    last_processed_row: Annotated[int, Field(strict=True, ge=0)]
    has_error_report: StrictBool
    failure_summary: Optional[Annotated[str, Field(strict=True, max_length=160)]]
    row_errors: Annotated[List[CommercialImportDetailEnvelopeDataRowErrorsInner], Field(max_length=100)]
    row_errors_truncated: StrictBool
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "kind", "status", "file_name", "dry_run", "sheet_name", "total_rows", "imported_rows", "rejected_rows", "last_processed_row", "has_error_report", "failure_summary", "row_errors", "row_errors_truncated", "started_at", "completed_at", "created_at", "updated_at"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['products', 'partners', 'supplier_offers', 'price_books']):
            raise ValueError("must be one of enum values ('products', 'partners', 'supplier_offers', 'price_books')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'processing', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('queued', 'processing', 'completed', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommercialImportDetailEnvelopeData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in row_errors (list)
        _items = []
        if self.row_errors:
            for _item_row_errors in self.row_errors:
                if _item_row_errors:
                    _items.append(_item_row_errors.to_dict())
            _dict['row_errors'] = _items
        # set to None if sheet_name (nullable) is None
        # and model_fields_set contains the field
        if self.sheet_name is None and "sheet_name" in self.model_fields_set:
            _dict['sheet_name'] = None

        # set to None if failure_summary (nullable) is None
        # and model_fields_set contains the field
        if self.failure_summary is None and "failure_summary" in self.model_fields_set:
            _dict['failure_summary'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommercialImportDetailEnvelopeData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "status": obj.get("status"),
            "file_name": obj.get("file_name"),
            "dry_run": obj.get("dry_run"),
            "sheet_name": obj.get("sheet_name"),
            "total_rows": obj.get("total_rows"),
            "imported_rows": obj.get("imported_rows"),
            "rejected_rows": obj.get("rejected_rows"),
            "last_processed_row": obj.get("last_processed_row"),
            "has_error_report": obj.get("has_error_report"),
            "failure_summary": obj.get("failure_summary"),
            "row_errors": [CommercialImportDetailEnvelopeDataRowErrorsInner.from_dict(_item) for _item in obj["row_errors"]] if obj.get("row_errors") is not None else None,
            "row_errors_truncated": obj.get("row_errors_truncated"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


