# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateCommercialImportRequest(BaseModel):
    """
    CreateCommercialImportRequest
    """ # noqa: E501
    kind: StrictStr
    file_name: Annotated[str, Field(min_length=1, strict=True, max_length=240)] = Field(alias="fileName")
    storage_key: Annotated[str, Field(min_length=1, strict=True, max_length=500)] = Field(alias="storageKey")
    content_sha256: Annotated[str, Field(strict=True)] = Field(alias="contentSha256")
    size_bytes: Annotated[int, Field(strict=True, gt=0)] = Field(alias="sizeBytes")
    sheet_name: Optional[Annotated[str, Field(strict=True, max_length=240)]] = Field(default=None, alias="sheetName")
    mapping: Optional[Dict[str, Any]] = None
    auto_match_enabled: Optional[StrictBool] = Field(default=None, alias="autoMatchEnabled")
    dry_run: Optional[StrictBool] = Field(default=None, alias="dryRun")
    __properties: ClassVar[List[str]] = ["kind", "fileName", "storageKey", "contentSha256", "sizeBytes", "sheetName", "mapping", "autoMatchEnabled", "dryRun"]

    @field_validator('content_sha256')
    def content_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{64}$/")
        return value

    @field_validator('auto_match_enabled')
    def auto_match_enabled_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['false']):
            raise ValueError("must be one of enum values ('false')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCommercialImportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCommercialImportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "kind": obj.get("kind"),
            "fileName": obj.get("fileName"),
            "storageKey": obj.get("storageKey"),
            "contentSha256": obj.get("contentSha256"),
            "sizeBytes": obj.get("sizeBytes"),
            "sheetName": obj.get("sheetName"),
            "mapping": obj.get("mapping"),
            "autoMatchEnabled": obj.get("autoMatchEnabled"),
            "dryRun": obj.get("dryRun")
        })
        return _obj


