# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateWebhookEndpointRequestSubscriptionsInner(BaseModel):
    """
    CreateWebhookEndpointRequestSubscriptionsInner
    """ # noqa: E501
    event_type: StrictStr = Field(alias="eventType")
    store_id: Optional[UUID] = Field(alias="storeId")
    __properties: ClassVar[List[str]] = ["eventType", "storeId"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['catalog.publication.completed.v1', 'alert.rule.created.v1', 'alert.rule.updated.v1', 'alert.rule.deleted.v1', 'alert.event.created.v1', 'commercial.product.created.v1', 'commercial.product.updated.v1', 'commercial.product.deleted.v1', 'commercial.partner.created.v1', 'commercial.partner.updated.v1', 'commercial.partner.deleted.v1', 'commercial.supplier_offer.created.v1', 'commercial.supplier_offer.updated.v1', 'commercial.supplier_offer.deleted.v1', 'commercial.price_book.created.v1', 'commercial.price_book.updated.v1', 'commercial.price_book.deleted.v1', 'commercial.market_link.created.v1', 'commercial.market_link.updated.v1', 'commercial.market_link.deleted.v1', 'commercial.import.completed.v1', 'commercial.import.failed.v1', 'commercial.import.cancelled.v1', 'repricer.settings.updated.v1', 'repricer.policy.created.v1', 'repricer.policy.updated.v1', 'repricer.policy.deleted.v1', 'repricer.exclusion.created.v1', 'repricer.exclusion.deleted.v1', 'repricer.run.completed.v1', 'repricer.run.failed.v1', 'repricer.run.cancelled.v1', 'repricer.recommendation.updated.v1', 'repricer.application.completed.v1', 'repricer.application.failed.v1', 'report.completed.v1', 'report.failed.v1', 'export.completed.v1', 'export.failed.v1', 'export.cancelled.v1', 'endpoint.test.v1']):
            raise ValueError("must be one of enum values ('catalog.publication.completed.v1', 'alert.rule.created.v1', 'alert.rule.updated.v1', 'alert.rule.deleted.v1', 'alert.event.created.v1', 'commercial.product.created.v1', 'commercial.product.updated.v1', 'commercial.product.deleted.v1', 'commercial.partner.created.v1', 'commercial.partner.updated.v1', 'commercial.partner.deleted.v1', 'commercial.supplier_offer.created.v1', 'commercial.supplier_offer.updated.v1', 'commercial.supplier_offer.deleted.v1', 'commercial.price_book.created.v1', 'commercial.price_book.updated.v1', 'commercial.price_book.deleted.v1', 'commercial.market_link.created.v1', 'commercial.market_link.updated.v1', 'commercial.market_link.deleted.v1', 'commercial.import.completed.v1', 'commercial.import.failed.v1', 'commercial.import.cancelled.v1', 'repricer.settings.updated.v1', 'repricer.policy.created.v1', 'repricer.policy.updated.v1', 'repricer.policy.deleted.v1', 'repricer.exclusion.created.v1', 'repricer.exclusion.deleted.v1', 'repricer.run.completed.v1', 'repricer.run.failed.v1', 'repricer.run.cancelled.v1', 'repricer.recommendation.updated.v1', 'repricer.application.completed.v1', 'repricer.application.failed.v1', 'report.completed.v1', 'report.failed.v1', 'export.completed.v1', 'export.failed.v1', 'export.cancelled.v1', 'endpoint.test.v1')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateWebhookEndpointRequestSubscriptionsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if store_id (nullable) is None
        # and model_fields_set contains the field
        if self.store_id is None and "store_id" in self.model_fields_set:
            _dict['storeId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateWebhookEndpointRequestSubscriptionsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventType": obj.get("eventType"),
            "storeId": obj.get("storeId")
        })
        return _obj


