# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateExportRequest(BaseModel):
    """
    CreateExportRequest
    """ # noqa: E501
    profile: Optional[StrictStr] = Field(default=None, description="Lossless machine profile: ZIP with integration.csv (record_json column) and metadata.json. Exact decimal strings, stable IDs, UTC timestamps and publication provenance.")
    dataset: StrictStr
    format: StrictStr
    locale: StrictStr
    timezone: StrictStr
    columns: Annotated[List[StrictStr], Field(min_length=1)]
    filters: Optional[Dict[str, Any]] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=120)]] = None
    __properties: ClassVar[List[str]] = ["profile", "dataset", "format", "locale", "timezone", "columns", "filters", "name"]

    @field_validator('profile')
    def profile_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['integration_v1']):
            raise ValueError("must be one of enum values ('integration_v1')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateExportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateExportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "profile": obj.get("profile"),
            "dataset": obj.get("dataset"),
            "format": obj.get("format"),
            "locale": obj.get("locale"),
            "timezone": obj.get("timezone"),
            "columns": obj.get("columns"),
            "filters": obj.get("filters"),
            "name": obj.get("name")
        })
        return _obj


