# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAlertRuleRequest(BaseModel):
    """
    CreateAlertRuleRequest
    """ # noqa: E501
    condition: StrictStr
    product_id: Optional[UUID] = Field(default=None, alias="productId")
    product_name: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(default=None, alias="productName")
    store_ids: Optional[List[UUID]] = Field(default=None, alias="storeIds")
    brand_ids: Optional[List[UUID]] = Field(default=None, alias="brandIds")
    category_ids: Optional[List[UUID]] = Field(default=None, alias="categoryIds")
    threshold_price: Optional[Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]]] = Field(default=None, alias="thresholdPrice")
    threshold_percent: Optional[Union[Annotated[float, Field(le=100, strict=True, gt=0)], Annotated[int, Field(le=100, strict=True, gt=0)]]] = Field(default=None, alias="thresholdPercent")
    notify_email: Optional[StrictBool] = Field(default=None, alias="notifyEmail")
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["condition", "productId", "productName", "storeIds", "brandIds", "categoryIds", "thresholdPrice", "thresholdPercent", "notifyEmail", "isActive"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAlertRuleRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if product_id (nullable) is None
        # and model_fields_set contains the field
        if self.product_id is None and "product_id" in self.model_fields_set:
            _dict['productId'] = None

        # set to None if product_name (nullable) is None
        # and model_fields_set contains the field
        if self.product_name is None and "product_name" in self.model_fields_set:
            _dict['productName'] = None

        # set to None if threshold_price (nullable) is None
        # and model_fields_set contains the field
        if self.threshold_price is None and "threshold_price" in self.model_fields_set:
            _dict['thresholdPrice'] = None

        # set to None if threshold_percent (nullable) is None
        # and model_fields_set contains the field
        if self.threshold_percent is None and "threshold_percent" in self.model_fields_set:
            _dict['thresholdPercent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAlertRuleRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "condition": obj.get("condition"),
            "productId": obj.get("productId"),
            "productName": obj.get("productName"),
            "storeIds": obj.get("storeIds"),
            "brandIds": obj.get("brandIds"),
            "categoryIds": obj.get("categoryIds"),
            "thresholdPrice": obj.get("thresholdPrice"),
            "thresholdPercent": obj.get("thresholdPercent"),
            "notifyEmail": obj.get("notifyEmail"),
            "isActive": obj.get("isActive")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


