# coding: utf-8

"""
    Rivalika Public API

    Stable business integration API for Rivalika customers.

    The version of the OpenAPI document: 1.0.0-beta.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateSupplierOfferRequest(BaseModel):
    """
    UpdateSupplierOfferRequest
    """ # noqa: E501
    product_id: Optional[UUID] = Field(default=None, alias="productId")
    partner_id: Optional[UUID] = Field(default=None, alias="partnerId")
    supplier_sku: Optional[StrictStr] = Field(default=None, alias="supplierSku")
    cost_amount: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="costAmount")
    currency: Optional[StrictStr] = None
    min_order_quantity: Optional[Annotated[int, Field(strict=True, gt=0)]] = Field(default=None, alias="minOrderQuantity")
    lead_time_days: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="leadTimeDays")
    valid_from: Optional[date] = Field(default=None, alias="validFrom")
    valid_to: Optional[date] = Field(default=None, alias="validTo")
    is_preferred: Optional[StrictBool] = Field(default=None, alias="isPreferred")
    __properties: ClassVar[List[str]] = ["productId", "partnerId", "supplierSku", "costAmount", "currency", "minOrderQuantity", "leadTimeDays", "validFrom", "validTo", "isPreferred"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateSupplierOfferRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if supplier_sku (nullable) is None
        # and model_fields_set contains the field
        if self.supplier_sku is None and "supplier_sku" in self.model_fields_set:
            _dict['supplierSku'] = None

        # set to None if min_order_quantity (nullable) is None
        # and model_fields_set contains the field
        if self.min_order_quantity is None and "min_order_quantity" in self.model_fields_set:
            _dict['minOrderQuantity'] = None

        # set to None if lead_time_days (nullable) is None
        # and model_fields_set contains the field
        if self.lead_time_days is None and "lead_time_days" in self.model_fields_set:
            _dict['leadTimeDays'] = None

        # set to None if valid_from (nullable) is None
        # and model_fields_set contains the field
        if self.valid_from is None and "valid_from" in self.model_fields_set:
            _dict['validFrom'] = None

        # set to None if valid_to (nullable) is None
        # and model_fields_set contains the field
        if self.valid_to is None and "valid_to" in self.model_fields_set:
            _dict['validTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateSupplierOfferRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "productId": obj.get("productId"),
            "partnerId": obj.get("partnerId"),
            "supplierSku": obj.get("supplierSku"),
            "costAmount": obj.get("costAmount"),
            "currency": obj.get("currency"),
            "minOrderQuantity": obj.get("minOrderQuantity"),
            "leadTimeDays": obj.get("leadTimeDays"),
            "validFrom": obj.get("validFrom"),
            "validTo": obj.get("validTo"),
            "isPreferred": obj.get("isPreferred")
        })
        return _obj


